title: VinUniversity Redcap 
description: A secure web application designed for data collection and management in research studies for Vinuniversity
theme: just-the-docs

url: https://sirius8611.github.io/redcap 

color_scheme: dark

